name: Build + Test

on: push

jobs:
  lint:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: README.md
          debug: true
          fail_on_error: true
          reporter: github-check
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  styles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Install Vale
        run: |
          go install github.com/errata-ai/vale/v2/cmd/vale@latest
          echo 'export PATH=$PATH:$(go env GOPATH)/bin' >> $GITHUB_PATH

      - name: Run tests
        run: |
          go test -v .
